"""
Ejecutar UNA sola vez para poblar la base de datos inicial.
  python seed_data.py
"""
from app import create_app
from extensions import db
from models.usuario import Usuario
from models.programa import Programa

PROGRAMAS = [
    ('EPG', 'EPG', 'ESCUELA DE POST GRADO', 44733.50),
    ('MAESTRIA', 'FAC AGRONOMIA', 'PROGRAMA DE MAESTRIA EN CIENCIAS AGRARIAS - PROMAGRO', 13412.00),
    ('DOCTORADO', 'FAC AGRONOMIA', 'PROGRAMA DE DOCTORADO EN CIENCIAS AGRARIAS - PRODOCIAG', 35067.50),
    ('MAESTRIA', 'FAC ARQUITECTURA Y URBANISMO', 'PROGRAMA DE MAESTRIA EN ARQUITECTURA - PROMARQ', 21287.00),
    ('MAESTRIA', 'FAC CIENCIAS', 'PROGRAMA DE MAESTRIA EN MATEMATICA APLICADA - PROMATE', 26011.00),
    ('MAESTRIA', 'FAC CIENCIAS', 'PROGRAMA DE MAESTRIA EN CIENCIAS DEL MAR - PROMACIMAR', 8700.00),
    ('MAESTRIA', 'FAC CIENCIAS', 'PROGRAMA DE MAESTRIA EN INGENIERIA ELECTRONICA Y CONTROL - PROMAINGESYC', 0.00),
    ('DOCTORADO', 'FAC CIENCIAS', 'PROGRAMA DE DOCTORADO EN CIENCIAS MATEMATICAS - PRODOCIMAT', 33444.10),
    ('MAESTRIA', 'FAC CIENCIAS ADMINISTRATIVAS', 'PROGRAMA DE MAESTRIA EN ADMINISTRACION - PROMAD', 219930.60),
    ('DOCTORADO', 'FAC CIENCIAS ADMINISTRATIVAS', 'PROGRAMA DE DOCTORADO EN CIENCIAS ADMINISTRATIVAS - PRODOCIAD', 66851.50),
    ('MAESTRIA', 'FAC CIENCIAS CONTABLES', 'PROGRAMA DE MAESTRIA EN CIENCIAS CONTABLES - PROMACCOF', 120496.00),
    ('DOCTORADO', 'FAC CIENCIAS CONTABLES', 'PROGRAMA DE DOCTORADO EN CONTABILIDAD Y FINANZAS - PRODOCOFF', 21617.34),
    ('MAESTRIA', 'FAC CIENCIAS DE LA SALUD', 'PROGRAMA DE MAESTRIA EN MEDICINA - PROMAMED - PIURA', 125623.10),
    ('DOCTORADO', 'FAC CIENCIAS DE LA SALUD', 'PROGRAMA DE DOCTORADO EN CIENCIAS DE LA SALUD - PRODOCISA', 24000.00),
    ('MAESTRIA', 'FAC CIENCIAS SOCIALES Y EDUCACION', 'PROGRAMA DE MAESTRIA EN EDUCACION - PROMACIEDU - PIURA', 150096.20),
    ('MAESTRIA', 'FAC CIENCIAS SOCIALES Y EDUCACION', 'PROGRAMA DE MAESTRIA EN CIENCIAS SOCIALES - GERENCIA SOCIAL', 19950.00),
    ('DOCTORADO', 'FAC CIENCIAS SOCIALES Y EDUCACION', 'PROGRAMA DE DOCTORADO EN CIENCIAS DE LA EDUCACION - PRODOCIEDU', 63838.40),
    ('MAESTRIA', 'FAC DERECHO Y CIENCIAS POLITICAS', 'PROGRAMA DE MAESTRIA EN DERECHO - PROMADE', 129501.95),
    ('DOCTORADO', 'FAC DERECHO Y CIENCIAS POLITICAS', 'PROGRAMA DE DOCTORADO EN DERECHO Y CIENCIAS POLITICAS - PRODODECIP', 75935.10),
    ('MAESTRIA', 'FAC ECONOMIA', 'PROGRAMA DE MAESTRIA EN CIENCIAS ECONOMICAS - PROMACE', 41318.90),
    ('DOCTORADO', 'FAC ECONOMIA', 'PROGRAMA DE DOCTORADO EN CIENCIAS ECONOMICAS Y FINANCIERAS - PRODOCEF', 6890.00),
    ('MAESTRIA', 'FAC INGENIERIA CIVIL', 'PROGRAMA DE MAESTRIA EN INGENIERIA CIVIL - PROMAINCI', 92673.70),
    ('MAESTRIA', 'FAC INGENIERIA DE MINAS', 'PROGRAMA DE MAESTRIA EN INGENIERIA AMBIENTAL Y SEGURIDAD INDUSTRIAL - PROMAINA', 108010.00),
    ('MAESTRIA', 'FAC INGENIERIA DE MINAS', 'PROGRAMA DE MAESTRIA EN SEGURIDAD INDUSTRIAL SALUD OCUPACIONAL - PROMASISOR', 49780.50),
    ('MAESTRIA', 'FAC INGENIERIA DE MINAS', 'PROGRAMA DE MAESTRIA EN INGENIERIA DE PETROLEO Y GAS NATURAL', 55587.00),
    ('MAESTRIA', 'FAC INGENIERIA DE MINAS', 'PROGRAMA DE MAESTRIA EN GESTION Y MANEJO RECURSOS HIDRICOS', 17600.00),
    ('MAESTRIA', 'FAC INGENIERIA DE MINAS', 'MAESTRIA EN GEOMECANICA MINERA', 6000.00),
    ('DOCTORADO', 'FAC INGENIERIA DE MINAS', 'PROGRAMA DE DOCTORADO EN CIENCIAS AMBIENTALES - PRODOCIAM', 41982.30),
    ('MAESTRIA', 'FAC INGENIERIA INDUSTRIAL', 'PROGRAMA DE MAESTRIA EN INFORMATICA - PROMAINFO', 3600.00),
    ('MAESTRIA', 'FAC INGENIERIA INDUSTRIAL', 'PROGRAMA DE MAESTRIA EN DIRECCION Y GESTION DE TI - PROMADGTICS', 20200.00),
    ('MAESTRIA', 'FAC INGENIERIA INDUSTRIAL', 'PROGRAMA DE MAESTRIA EN INGENIERIA INDUSTRIAL - PROMAINDU', 41425.10),
    ('DOCTORADO', 'FAC INGENIERIA INDUSTRIAL', 'PROGRAMA DE DOCTORADO EN INGENIERIA INDUSTRIAL - PRODOII', 6896.40),
    ('DOCTORADO', 'FAC INGENIERIA INDUSTRIAL', 'PROGRAMA DE DOCTORADO EN INGENIERIA DE SISTEMAS - PRODOCIS', 0.00),
    ('DOCTORADO', 'FAC INGENIERIA INDUSTRIAL', 'PROGRAMA DE DOCTORADO EN TIC - PRODOTICS', 0.00),
    ('MAESTRIA', 'FAC INGENIERIA PESQUERA', 'PROGRAMA DE MAESTRIA EN INGENIERIA PESQUERA - PROMAINPE', 31043.50),
]

USUARIOS = [
    ('tesorera', 'epg2026', 'Tesorera EPG', 'tesorera'),
    ('operador', 'epg2026', 'Operador EPG', 'operador'),
    ('admin', 'admin2026', 'Administrador EPG', 'admin'),
]


def seed():
    app = create_app()
    with app.app_context():
        # Usuarios
        for username, password, nombre, rol in USUARIOS:
            if not Usuario.query.filter_by(username=username).first():
                u = Usuario(username=username, nombre_completo=nombre, rol=rol)
                u.set_password(password)
                db.session.add(u)
                print(f'  [+] Usuario: {username}')

        # Programas
        for tipo, facultad, mencion, ingresos in PROGRAMAS:
            if not Programa.query.filter_by(mencion=mencion).first():
                p = Programa(tipo_programa=tipo, facultad=facultad,
                             mencion=mencion, ingresos=ingresos)
                db.session.add(p)
                print(f'  [+] Programa: {mencion[:50]}...' if len(mencion) > 50 else f'  [+] Programa: {mencion}')

        db.session.commit()
        print('\nSeed completado. 35 programas y 3 usuarios creados.')


if __name__ == '__main__':
    print('Iniciando seed...')
    seed()
